import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import css from "../styles/Home.module.scss";
import { polishReverse } from "../domain/index";

const Home: NextPage = () => {
  const [calcul, setCalcul] = useState<string>("");

  function addCharacter(chara: string) {
    const newCalcul = calcul + chara;
    setCalcul(newCalcul);
  }

  function clearChara() {
    setCalcul("");
  }

  function resultCalcul() {
    setCalcul(polishReverse(calcul));
  }

  return (
    <div className={css.container}>
      <Head>
        <title>Calculateur d’expressions RPN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={css.main}>
        <h1>
          Calculateur d’expressions <span>en notation polonaise inversée</span>
        </h1>
        <div className={css.calculator}>
          <div className={css.input} id="input">
            {calcul}
          </div>
          <div className={css.buttons}>
            <div className={css.operators}>
              <div onClick={() => addCharacter("+")}>+</div>
              <div onClick={() => addCharacter("-")}>-</div>
              <div onClick={() => addCharacter("*")}>&times;</div>
              <div onClick={() => addCharacter("/")}>&divide;</div>
            </div>
            <div className={css.leftPanel}>
              <div className={css.numbers}>
                <div onClick={() => addCharacter("7")}>7</div>
                <div onClick={() => addCharacter("8")}>8</div>
                <div onClick={() => addCharacter("9")}>9</div>
              </div>
              <div className={css.numbers}>
                <div onClick={() => addCharacter("4")}>4</div>
                <div onClick={() => addCharacter("5")}>5</div>
                <div onClick={() => addCharacter("6")}>6</div>
              </div>
              <div className={css.numbers}>
                <div onClick={() => addCharacter("1")}>1</div>
                <div onClick={() => addCharacter("2")}>2</div>
                <div onClick={() => addCharacter("3")}>3</div>
              </div>
              <div className={css.numbers}>
                <div onClick={() => addCharacter("0")}>0</div>
                <div id="clear" onClick={() => clearChara()}>
                  C
                </div>
              </div>
            </div>
            <div
              className={css.equal}
              id="result"
              onClick={() => resultCalcul()}
            >
              =
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
